[versions]
detekt = "1.23.8"
fabrikt = "1.39.1"
jackson = "2.22.2"
kotlin = "2.4.10"
ksp = "2.3.11"
ktfmt = "0.27.0"
okhttp = "5.5.0"
logback = "1.5.32"
micronaut-plugin = "4.6.2" # The last of the 4.x line, supporting Java 21
shadow = "9.6.1"
versionCatalogUpdate = "1.1.1"

[libraries]
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
fabrikt = { id = "ch.acanda.gradle.fabrikt", version.ref = "fabrikt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
micronaut-library = { id = "io.micronaut.library", version.ref = "micronaut-plugin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
versionCatalogUpdate = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdate" }
