name: Check PR

on:
  pull_request:

permissions:
  contents: read

jobs:
  check-gh-workflows:
    name: GitHub workflows
    uses: ./.github/workflows/check-gh-workflows.yml

  check-config:
    name: Config
    uses: ./.github/workflows/check-config.yml

  check-root-infra:
    name: Root infra
    uses: ./.github/workflows/check-root-infra.yml

  check-backend-impl:
    name: Backend implementation
    uses: ./.github/workflows/check-backend-impl.yml

  check-web-app-impl:
    name: Web app implementation
    uses: ./.github/workflows/check-web-app-impl.yml

  check-backend-infra:
    name: Backend infra
    uses: ./.github/workflows/check-backend-infra.yml

  check-web-app-infra:
    name: Web app infra
    uses: ./.github/workflows/check-web-app-infra.yml
